import { StyleSheet } from 'react-native'

const styleForm = StyleSheet.create({
    formContext:{
        width:"100%",
        height:"100%",
        justifyContent:"space-around",
        bottom:0,
        backgroundColor:"#ffffff",
        alignItems:"center",
        borderTopLeftRadius:30,
        borderTopRightRadius:30,
        marginTop:20,
        paddingTop:30
    },
    form:{
        width:"100%",
        height:"auto",
    },
    formLabel:{
        color:"#000000",
        fontSize:18,
        paddingLeft:20
    },
    formInput:{
        width:"90%",
        borderRadius:50,
        backgroundColor:"lightgray",
        margin:12,
        paddingLeft:10,
        height:40,
    },
    buttonCalculador:{
        borderRadius:50,
        alignItems:"center",
        justifyContent:"center",
        width:"90%",
        backgroundColor:"#ff0043",
        paddingTop:14,
        paddingBottom:14,
        marginLeft:12,
        marginTop:30
    },
    textButtonCalculator:{
        fontSize:20,
        color:"#fff"
    },
    errorMessage:{
        fontSize:12,
        color:'red',
        fontWeight:"bold",
        paddingLeft:20,        
    },
    exibitionResultImc:{
        width:"100%",
        height:"50%"
    }
})
export default styleForm